# Generated by Django 6.0.6 on 2026-09-30 15:58

import django.core.validators
import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotel_cover_alter_hotel_rating_hotel_hotel_city_idx_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG/PNG/WEBP, не более 5 МБ', null=True, upload_to=rooms.models.room_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото номера'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_available', 'room_type'], name='room_is_available_room_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='room_unique_number_hotel'),
        ),
    ]
