# Generated by Django 6.0.6 on 2026-09-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_image_room_room_is_available_room_type_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='room',
            new_name='room_available_type_idx',
            old_name='room_is_available_room_type_idx',
        ),
    ]
