# Generated by Django 6.0.6 on 2026-09-30 16:01

import core.validators
import django.core.validators
import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_room_is_available_room_type_idx_room_available_type_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG/PNG/WEBP, не более 5 МБ', null=True, upload_to=rooms.models.room_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_images_size], verbose_name='Фото номера'),
        ),
    ]
