# Generated by Django 6.0.6 on 2026-10-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='FAQItem',
        ),
        migrations.DeleteModel(
            name='PromoOffer',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
