# Generated by Django 6.0.6 on 2026-06-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_is_active_hotel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
    ]
