# Generated by Django 6.0.6 on 2026-06-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
    ]
