# Generated by Django 6.0.6 on 2026-06-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='price',
            new_name='price_night',
        ),
    ]
