# Generated by Django 6.0.6 on 2026-07-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_rename_price_hotel_price_night'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
    ]
