# Generated by Django 6.0.6 on 2026-09-30 15:58

import core.validators
import django.core.validators
import hotels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cover',
            field=models.ImageField(blank=True, help_text='JPG/PNG/WEBP, не более 5 МБ.', null=True, upload_to=hotels.models.hotel_cover_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_images_size], verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city'], name='hotel_city_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_active', '-rating'], name='hotel_active_rating_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='hotel_rating_between_0_and_5'),
        ),
    ]
