# Generated by Django 6.0.6 on 2026-06-30 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_check_in', models.DateTimeField()),
                ('date_check_out', models.DateTimeField()),
                ('status', models.CharField(choices=[('boocked', 'Забронирован'), ('free', 'Свободен')], default='free', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_room', to='rooms.room')),
            ],
        ),
    ]
