# Generated by Django 6.0.6 on 2026-09-29 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Гость'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-created_at'], name='booking_user_created_at-idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'status'], name='bookings_bo_room_id_97310a_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='booking_checkout_after_checkin'),
        ),
    ]
