# Generated by Django 6.0.6 on 2026-06-30 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_email', models.CharField(blank=True, max_length=64, unique=True)),
                ('date_of_check_in', models.DateTimeField()),
                ('date_check_out', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждена'), ('canselled', 'Отменена')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
